---

- name: Set VM values
  ansible.builtin.set_fact:
    # network
    nics:
      -
        name: enp1s0
        mac: "{{ public_mac_prefix }}:00:03"
        net: "{{ public_libvirt_name }}"
        # IP comes from the public network's DHCP service
        # eg. 192.168.1.234
      -
        name: enp2s0
        mac: "{{ lab_mac_prefix }}:00:03"
        net: "{{ lab_libvirt_name }}"
        # IP is static
        ip: "{{ lab_net_prefix }}.3"
    net_services:
      - dns
      - http
      - https
      - ssh
    # OS
    fqdn: gateway.silvan.uk
    RPMs:
      - cockpit
      - httpd
      - squid
      - bind
    # kickstart
    kickstart_template: "gateway.ks.j2"

# create a few variables like "volume_image_file_exists"
- name: Add image facts to hostvars
  ansible.builtin.include_role:
    name: nickhardiman.libvirt.libvirt_image_facts

# !!! If there already is an image file, don't trash it. 

- name: "Kickstart VM on hypervisor {{ inventory_hostname }}"
  ansible.builtin.include_role:
    name: nickhardiman.libvirt.libvirt_machine_kickstart
